---
- include: ../../../python_apps.yml

- name: Create directory
  file: path={{ dev_home }}/data_manager state=directory

- name: Copy test file
  copy: src=test_connector.py dest={{ dev_home }}/data_manager/test_connector.py