---
# Playbook for recommander dev_home
# TODO: frontend conf
# TODO: USe vault to store passwords
- hosts: all
  user: recom
  vars:
    user_name: recom
    user_password: NWQ1NzY3ZT
    dev_home: /home/recom
    environment_type: dev
  roles:
    - graph_db
    - data_manager
    - api_server
    # - frontend