---
# Playbook for recommander dev_home
# TODO: frontend conf
# TODO: Use vault to store passwords
- hosts: all
  user: recom
  vars:
    user_name: recom
    # python -c 'import crypt; print crypt.crypt("NWQ1NzY3ZT", "Inc1rr1na;veryPR21V4TEs3cr3t!")'
    user_password: InpQ6KYcqImH.
    dev_home: /home/recom
    environment_type: dev
    user_home: /home/vagrant
  roles:
    - graph_db
    - data_manager
    - api_server
    # - frontend