---
- name: start neo4j
  sudo: true
  command: neo4j start

# - name: set database password
#   command: 'curl -H "Content-Type: application/json" -X POST -d ''{"password":"{{neo4j.password}}"}'' -u neo4j:neo4j http://localhost:7474/user/neo4j/password'