---
- include: ../../../python_apps.yml

- name: Install Flask
  sudo: true
  command: "{{ user_home }}/.conda/envs/{{ env_name}}/bin/pip install Flask"

- name: Create directory
  file: path={{ dev_home }}/api_server state=directory